# Site settings
title: Just Developer
email: hidder1984@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Interest in everthing will make us better, like Java, Javascript, HTML, CSS, Funcitonal programming, Big data.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jacobzeng.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  jacobzeng

# Build settings
markdown: kramdown
