# Site settings
title: Just Developer
email: hidder1984@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Interest in everthing will make us better, like Java, Javascript, HTML, CSS, Funcitonal programming, Big data.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jacobzeng.github.io" # the base hostname & protocol for your site

### Personal info and site tools info:
twitter_username: 
github_username:  jacobzeng
disqus_shortname: hidder
favicon:     "/images/favicon.ico"
aboutme: Hi, this is Ruilin Zeng， just Developer. # these are shown on aboutme-sidebar.
aboutme_photo: https://i.imgur.com/Mdc4szJl.jpg# your photo.
google_analytics_key:


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
      Google_search: "站内搜索"

# Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
excerpt_separator: <!-- more -->